name: Erme
version: 0.1
main: me.brofan11.erme.ErmeAPI
author: BroFan11
commands:
  adderme:
    command: /<command>
    aliases: [addérme, érmeadás, ermeadas, adás, hozzáadás]
  removeerme:
    command: /<command>
    aliases: [removeérme, ermeelvetel, érmeelvétel, elvétel, elvetel]
  seterme:
    command: /<command>
    aliases: [setérme, beállít, beállítás, beallit, beallitas]
  erme:
    command: /<command>
    aliases: [érme, érméim, ermeim]
  payerme:
    command: /<command>
    aliases: [payérme, utal, utalás]
  ermetop:
    command: /<command>
    aliases: [toplista, érmetop, topérme]
  ermereload:
    command: /<command>
  ermehelp:
    command: /<command>

